name: CI para SEVD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Ejecutar pruebas PHP (simulada)
      run: php -r "echo '✅ Entorno PHP listo para correr pruebas';"

    - name: Ejecutar pruebas PHPUnit
      run: vendor/bin/phpunit tests

